name: Upload Website

on:
  push:
    branches:
    - master

jobs:
  main:
    runs-on: ubuntu-latest
        
    steps:
      - name: checkout (latest)
        uses: actions/checkout@v1

      - name: use Node 12 (LTS)
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: use cached node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: nodeModules-${{hashFiles('./package-lock.json')}}
          restore-keys: |
            nodeModules-
      - name: install dependencies
        run: npm install --ignore-scripts
        env:
          CI: true
      - name: build
        run: npm run build
        env:
          CI: true

      - name: setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_REGION}}
      
      - name: deploy
        run: |
          aws s3 sync --delete ./build s3://${{secrets.AWS_PRODUCTION_BUCKET_NAME}}
          aws cloudfront create-invalidation \
            --region ${{secrets.AWS_REGION}} \
            --distribution-id ${{secrets.AWS_CF_ID}} \
            --paths "/*"
